[project]
name = "svavto-dry-cleaning-telegram-bot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.18.0",
    "fast-depends>=2.4.12",
    "httpx>=0.28.1",
    "python-json-logger>=3.3.0",
]
